AntCore/src/AntCore/Controllers/Siniestro/SiniestroController.cs
using System;
using System.Collections.Generic;

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Modelo.Entity;
using Modelo.Negocios;
using Model.Datos;
using Newtonsoft.Json; // Use for JsonConvert
using Microsoft.AspNetCore.Mvc.Rendering;
using excel = OfficeOpenXml;
using System.Text;
using Microsoft.AspNetCore.Http;
using Npgsql;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Xml.Linq;
using System.Linq;
using System.Xml.Serialization;
//using System.Web.Mvc.FilePathResult;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AntCore.Controllers.Siniestro
{
    public class SiniestroController : Controller
    {

       // DownloadFiles obj;
        private readonly IHostingEnvironment _hostingEnvironment;
        SiniestroNegocio objSiniestrosNeg;
       ProvinciasNegocio objProvinciasNeg;
       ProvinciasRepositorio provinciasRepository = null;
       const string SessionKeyCodUsuario = "_CodUsuario";
        private ConexionDB objConexinDB;
        private NpgsqlCommand comando;
        public SiniestroController(IHostingEnvironment environment)
        {
            objSiniestrosNeg = new SiniestroNegocio();
            provinciasRepository = new ProvinciasRepositorio();
            objProvinciasNeg = new ProvinciasNegocio();
            objConexinDB = ConexionDB.saberEstado();
            _hostingEnvironment = environment;
        }

        
        // GET: /<controller>/
        public IActionResult Index()
        {
            var codUsuario = HttpContext.Session.GetString(SessionKeyCodUsuario);
            string codAutoridad = HttpContext.Session.GetString("codAutoridad");
            List<Modelo.Entity.Siniestro> lista = objSiniestrosNeg.findAll(codAutoridad);
            if(codUsuario != "" && codUsuario != null)
                return View(lista);
            else
                return RedirectToAction("Index", "Login");


        }
        public  IActionResult Busqueda()
        {
            //objSiniestrosNeg.enviaMail();
            objSiniestrosNeg.ActualizaNombresVictimas();
            ViewBag.resultado = "";
            return View();
        }


        public IActionResult FindModificar()
        {
            var codUsuario = HttpContext.Session.GetString(SessionKeyCodUsuario);
            var codpermisoGeneral = HttpContext.Session.GetString("PermisoGeneral");
            var codpermisoSupervisor = HttpContext.Session.GetString("PermisoGeneral");
            string codAutoridad = HttpContext.Session.GetString("codAutoridad");
            List<Modelo.Entity.Siniestro> lista = objSiniestrosNeg.findAll(codAutoridad);
            if (codUsuario != "" && codUsuario != null)
                return View(lista);
            else
                return RedirectToAction("Index", "Login");
            //return View(lista);

        }
        
        public ActionResult FindSiniestro(int id)
        {
            var codUsuario = HttpContext.Session.GetString(SessionKeyCodUsuario);
            string codAutoridad = HttpContext.Session.GetString("codAutoridad");
            Vehiculo v = new Vehiculo();
            v.codsin = id;
            ViewBag.CodigoSiniestroFind = v.codsin.ToString();
            ViewBag.codAutoridad = codAutoridad.ToString();
            if (codUsuario != "" && codUsuario != null)
                return View(ListaVehiculos(v.codsin));
            else
                return RedirectToAction("Index", "Login");
        }

       
        public IActionResult CrearSiniestro()
        {
            var codUsuario = HttpContext.Session.GetString(SessionKeyCodUsuario);
            
            Modelo.Entity.Siniestro model = new Modelo.Entity.Siniestro()
            {
                provinciasLista = new SelectList(objSiniestrosNeg.listaProvincias(), "codprov", "nomprov"),
            };

            ViewBag.tipoZonaLista = ObtenerListadoTipoZona();
            ViewBag.ObtenerListadoCondicionAtmosferica = ObtenerListadoCondicionAtmosferica();
            ViewBag.ObtenerlistadatosCondicionVia = ObtenerlistadatosCondicionVia();
            ViewBag.ObtenerlistadatosLuzArtificial = ObtenerlistadatosLuzArtificial();
            ViewBag.ObtenerlistadatosTipoVia = ObtenerlistadatosTipoVia();
            ViewBag.ObtenerlistadatosLimiteVelocidad = ObtenerlistadatosLimiteVelocidad();
            ViewBag.ObtenerlistadatosControlInterseccion = ObtenerlistadatosControlInterseccion();
            ViewBag.ObtenerlistadatosMaterialSuperficieVia = ObtenerlistadatosMaterialSuperficieVia();
            ViewBag.ObtenerlistadatosObstaculoVia = ObtenerlistadatosObstaculoVia();
            ViewBag.ObtenerlistadatosLugarVia = ObtenerlistadatosLugarVia();
            ViewBag.ObtenerlistadatosNumeroCarriles = ObtenerlistadatosNumeroCarriles();
            ViewBag.ObtenerlistadatosSenialitica = ObtenerlistadatosSenialitica();
            ViewBag.ObtenerlistadatosTransporteMaterialPeligroso = ObtenerlistadatosTransporteMaterialPeligroso();
            ViewBag.ObtenerListaTipoVehiculo = ObtenerListaTipoVehiculo();
            ViewBag.ObtenerlistaServiciosVehiculos = ObtenerlistaServiciosVehiculos();
            ViewBag.ObtenerlistaTipoDaniosTerceros = ObtenerlistaTipoDaniosTerceros();
            ViewBag.ObtenerlistadatosTipoIdentificacion = ObtenerlistadatosTipoIdentificacion();
            ViewBag.ObtenerlistadatosSexo = ObtenerlistadatosSexo();
            ViewBag.ObtenerlistadatosCondicionVictimas24 = ObtenerlistadatosCondicionVictimas24();
            ViewBag.ObtenerlistadatosCondicionVictimas30 = ObtenerlistadatosCondicionVictimas30();
            ViewBag.ObtenerlistadatosTipoParticipante = ObtenerlistadatosTipoParticipante();
            ViewBag.ObtenerlistadatosPosicionPlaza = ObtenerlistadatosPosicionPlaza();
            ViewBag.ObtenerlistadatosAccionesPeaton = ObtenerlistadatosAccionesPeaton();
            ViewBag.ObtenerlistadatosCurvaExistente = ObtenerlistadatosCurvaExistente();
            ViewBag.ObtenerlistatipoSiniestros = ObtenerlistatipoSiniestros();
            ViewBag.ObtenerlistaCausaProbableSiniestros = ObtenerlistaCausaProbableSiniestros();
            ViewBag.ObtenerlistaCausaRealSiniestros = ObtenerlistaCausaRealSiniestros();
            ViewBag.ObtenerListaVheiculos = ListaVehiculos(399);
            string codAutoridad = HttpContext.Session.GetString("codAutoridad");
            ViewBag.ObtenerlistaGeoreferencias = listaGeoreferencias(codAutoridad);
            ViewBag.ObtenerlistaParroquias = ObtenerlistaParroquias();
            ViewBag.ObtenerlistaTodosCiruitos = ObtenerlistaTodosCiruitos();
            ViewBag.ObtenerlistaTodosDistritos = ObtenerlistaTodosDistritos();

            ViewBag.ObtenerlistadatosValoresSiNo = ObtenerlistadatosValoresSiNo();
            string mes = Convert.ToString( DateTime.Now.Month.ToString()).Length == 1 ? "0"+""+ Convert.ToString(DateTime.Now.Month.ToString()) : Convert.ToString(DateTime.Now.Month.ToString());
            string dia = Convert.ToString(DateTime.Now.Day.ToString()).Length == 1 ? "0" + "" + Convert.ToString(DateTime.Now.Day.ToString()) : Convert.ToString(DateTime.Now.Day.ToString());
            string hora = Convert.ToString(DateTime.Now.Hour.ToString()).Length == 1 ? "0" + "" + Convert.ToString(DateTime.Now.Hour.ToString()) : Convert.ToString(DateTime.Now.Hour.ToString());
            string minuto = Convert.ToString(DateTime.Now.Minute.ToString()).Length == 1 ? "0" + "" + Convert.ToString(DateTime.Now.Minute.ToString()) : Convert.ToString(DateTime.Now.Minute.ToString());
            model.fecsin = DateTime.Now.Year.ToString() + '-' + mes +'-'+ dia;
            model.horsin = hora+':'+minuto;
            if (codUsuario != "" && codUsuario != null)
                return View(model);
            else
                return RedirectToAction("Index", "Login");

          
        }

        public JsonResult listaGeoreferenciasAppMovil(int coudusuario)
        {
            var jsonResult = listaGeoreferenciasMovil(coudusuario);
            return Json(jsonResult);
        }

        public ActionResult CargaDatosView(int id)
        {
            ViewBag.ObtenerlistaParroquias = ObtenerlistaParroquias();
            ViewBag.ObtenerlistaTodosCiruitos = ObtenerlistaTodosCiruitos();
            ViewBag.ObtenerlistaTodosDistritos = ObtenerlistaTodosDistritos();
            return View();
        }
        public IActionResult CargaDistritosPorCodigo(int codcant)
        {
            ViewBag.ObtenerlistaCiruitos = ObtenerlistaCiruitos(Convert.ToInt32(1701), Convert.ToInt32(0));
            return View("CrearSiniestro");
        }
        public JsonResult ObtenerPlacaVehiculo(string parametro, string opcion)
        {
            var jsonResult = ObtenerPlacaVhl(parametro, opcion);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaGeoreferencias(string codaut)
        {
            var jsonResult = listaGeoreferencias(codaut);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaVistaSiniestros(int codsin)
        {
            var jsonResult = listaVistaSiniestros(codsin);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaVistaAccionesPeatones(int codsin)
        {
            var jsonResult = listaVistaAccionesPeatones(codsin);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaVistaDaniosTerceros(int codsin)
        {
            var jsonResult = listaVistaDaniosTerceros(codsin);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaPeaton(int codsin)
        {
            var jsonResult = ObtenerlistaPeatones(codsin);
            return Json(jsonResult);
        }
        public JsonResult ObtenerlistaVictimasInvolucrados(int codsin)
        {

AntCore/src/AntCore/Views/Siniestro/Busqueda.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>dasdas</h2> 

<div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
    #Identificación*
    @Html.TextBox("tb_IdentificacionVictima1", null, new { @class = "form-control", @placeholder = "#Indentificación", maxlength = "10" })
</div>
<div class="col-xs-12 col-sm-4 col-md-3 col-lg-1">
    <br />
    <a class="btn btn-outline btn-default active"  id="btnBuscarVict1"><span class="glyphicon glyphicon-search">Buscar</span></a>
</div>
<div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
    Edad*
    @Html.TextBox("tb_edadVictima1", null, new { @class = "form-control", @placeholder = "Edad", onkeypress = "return NumCheckEdad(event, this)", maxlength = "2" })
</div>
<div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
    sexo*
    @Html.TextBox("tb_sexov1", null, new { @class = "form-control", @placeholder = "Edad", onkeypress = "return NumCheckEdad(event, this)", maxlength = "2" })
</div>
<div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
    nombres*
    @Html.TextBox("tb_NombresVictima1", null, new { @class = "form-control", @placeholder = "Edad", onkeypress = "return NumCheckEdad(event, this)", maxlength = "2" })
</div>
<div class="col-xs-12 col-sm-4 col-md-3 col-lg-1" id="divLoaderSinBus" style="display:none">
    <br />
    <img src="~/images/loadre.gif" />
</div>
<div class="form-group">
    <div ID="panelMensajeCal" Class="active smaller">
        <div id="divMensajeCal" class="alert alert-block alert-success fade in smaller">
            <strong><label ID="mensajeStrongLabelCal"> </label></strong>
            <label ID="mensajeLabelCal">@ViewBag.resultado</label>
        </div>
    </div>

</div>

AntCore/src/AntCore/Views/Siniestro/FindModificar.cshtml
@using Microsoft.AspNetCore.Http;
@model List<Modelo.Entity.Siniestro>
<div class="row">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                
                <div class="panel-heading">
                    <h5>Búsqueda Siniestros</h5>
                </div>
                <!-- /.panel-heading table table-bordered table-striped table-hover table-condensed table-layout small  style="table-layout:fixed"-->

                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover table-condensed table-layout small" style="table-layout:fixed" id="dt_siniestros">
                        <thead>

                            <tr class="bg-primary small"  >

                                <th>#Siniestro</th>
                                <th>Fecha</th>
                                <th>#Fallecidos</th>
                                <th>#Lesionados</th>
                                <th>Provincia</th>
                                <th>Cantón</th>
                                <th>Zona</th>
                                <th  >Dirección</th>
                                <th>Foto</th>
                                <th>Croquis</th>
                                <th>Estado</th>
                                <th>Registro Validado</th>
                                <th>Modififcar</th>



                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var objSin in Model)
                            {
                                @if (objSin.REGISTRO_VALIDADO.ToString() == "OK")
                                {
                                    <tr class="small">

                                        <td>@objSin.codsin</td>
                                        <td>@objSin.fecsin</td>
                                        <td>@objSin.numfalsin</td>
                                        <td>@objSin.numlessin</td>
                                        <td class="ajustar">@objSin.nomprov</td>
                                        <td class="ajustar">@objSin.descant</td>
                                        <td>@objSin.zonsin</td>
                                        <td   class="ajustar" > <small>@objSin.dirsin</small> </td>
                                        <td class="ajustar"><small><a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto1C" asp-controller="Siniestro" asp-route-id="@objSin.fotprigeo">@objSin.fotprigeo</a></small></td>
                                        <td class="ajustar">  
                                            <small> <a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto2C" asp-controller="Siniestro" asp-route-id="@objSin.fotsegeo">@objSin.fotsegeo</a></small>
                                        </td>
                                        <td>@objSin.desprocsin</td>
                                        <td>@objSin.REGISTRO_VALIDADO</td>

                                        <td>
                                            @*<a class="btn" id="btnEditarSiniestro" asp-action="Index" asp-controller="ModificarSiniestro" asp-route-id="@objSin.codsin"><p class="fa fa-pencil-square-o"></p></a>*@

                                        </td>
                                    </tr>

                                }
                                else if (objSin.REGISTRO_VALIDADO.ToString() == "PENDIENTE")
                                {
                                    <tr class="small danger"  >

                                        <td>@objSin.codsin</td>
                                        <td>@objSin.fecsin</td>
                                        <td>@objSin.numfalsin</td>
                                        <td>@objSin.numlessin</td>
                                        <td class="ajustar">@objSin.nomprov</td>
                                        <td class="ajustar">@objSin.descant</td>
                                        <td>@objSin.zonsin</td>
                                        <td class="ajustar"><small>@objSin.dirsin</small></td>
                                        <td class="ajustar">
                                            <a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto1C" asp-controller="Siniestro" asp-route-id="@objSin.fotprigeo">@objSin.fotprigeo</a>
                                   
                                        </td>
                                        <td class="ajustar">
                                            <a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto2C" asp-controller="Siniestro" asp-route-id="@objSin.fotsegeo">@objSin.fotsegeo</a>
                                       </td>
                                        <td>@objSin.desprocsin</td>
                                        <td>@objSin.REGISTRO_VALIDADO</td>

                                        <td>
                                            <a class="btn" id="btnEditarSiniestro" asp-action="Index" asp-controller="ModificarSiniestro" asp-route-id="@objSin.codsin"><p class="fa fa-pencil-square-o"></p></a>

                                        </td>


                                    </tr>
                                }
                            }
                        </tbody>

                    </table>
                </div>
                

                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>

AntCore/src/AntCore/Views/Siniestro/Index.cshtml
@using Microsoft.AspNetCore.Http;
@model List<Modelo.Entity.Siniestro>
<div class="row">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                @*@if (Context.Session.GetString("PermisoValidador") != "3")//((string)ViewBag.valorPermisoGeneral == "1")
                {
                    <a class="btn btn-link" asp-action="CrearSiniestro">Registrar Siniestro</a>
                }*@
           
               
                  
                
                <div class="panel-heading">
                    <h5>Búsqueda Siniestros</h5>
                </div>
                <!-- /.panel-heading -->
             
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover table-condensed table-layout small" style="table-layout:fixed" id="dt_siniestros">
                        <thead>

                            <tr class="bg-primary small">



                                <th>#Siniestro</th>
                                <th>Fecha</th>
                                <th>#Fallecidos</th>
                                <th>#Lesionados</th>
                                <th>Provincia</th>
                                <th>Cantón</th>
                                <th>Zona</th>
                                <th >Dirección</th>
                                <th>Foto</th>
                                <th>Croquis</th>
                                <th>Estado</th>
                                <th>Registro Validado</th>
                                <th>Validar</th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var objSin in Model)
                            {
                                @if (objSin.REGISTRO_VALIDADO.ToString() == "OK" )
                                {
                                    <tr class="small">

                                        <td>@objSin.codsin</td>
                                        <td>@objSin.fecsin</td>
                                        <td>@objSin.numfalsin</td>
                                        <td>@objSin.numlessin</td>
                                        <td class="ajustar">@objSin.nomprov</td>
                                        <td class="ajustar">@objSin.descant</td>
                                        <td>@objSin.zonsin</td>
                                        <td  class="ajustar" >  <small>@objSin.dirsin</small></td>
                                        <td class="ajustar"><a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto1C" asp-controller="Siniestro" asp-route-id="@objSin.fotprigeo">@objSin.fotprigeo</a></td>
                                        <td class="ajustar"><a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto2C" asp-controller="Siniestro" asp-route-id="@objSin.fotsegeo">@objSin.fotsegeo</a></td>
                                        <td>@objSin.desprocsin</td>
                                        <td>@objSin.REGISTRO_VALIDADO</td>
                                        <td>
                                            @*<a class="btn" id="btnModificarSiniestro" asp-action="FindSiniestro" asp-controller="Siniestro" asp-route-id="@objSin.codsin"><span class="glyphicon glyphicon-eye-open"></span></a>*@


                                        </td>

                                    </tr>

                                }
                                else if (objSin.REGISTRO_VALIDADO.ToString() == "PENDIENTE" )
                                {
                                    <tr class="danger small">



                                        <td>@objSin.codsin</td>
                                        <td>@objSin.fecsin</td>
                                        <td>@objSin.numfalsin</td>
                                        <td>@objSin.numlessin</td>
                                        <td class="ajustar">@objSin.nomprov</td>
                                        <td class="ajustar">@objSin.descant</td>
                                        <td>@objSin.zonsin</td>
                                        <td  class="ajustar" >  <small>@objSin.dirsin</small></td>
                                        <td class="ajustar"><a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto1C" asp-controller="Siniestro" asp-route-id="@objSin.fotprigeo">@objSin.fotprigeo</a></td>
                                        <td class="ajustar"><a class="btn-link" id="btnfotsegeo" asp-action="DownloadFoto2C" asp-controller="Siniestro" asp-route-id="@objSin.fotsegeo">@objSin.fotsegeo</a></td>
                                        <td>@objSin.desprocsin</td>
                                        <td>@objSin.REGISTRO_VALIDADO</td>

                                            <td>
                                                <a class="btn" id="btnModificarSiniestro" asp-action="FindSiniestro" asp-controller="Siniestro" asp-route-id="@objSin.codsin"><span class="glyphicon glyphicon-eye-open"></span></a>


                                            </td>
                                        
                                        

                                    </tr>
                                }
                            }
                        </tbody>

                    </table>

                </div>
              
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>