AntCore/src/AntCore/Controllers/CargaCalificaciones/CargaCalificacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using OfficeOpenXml;
using System.Text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Modelo.Entity;
using Modelo.Negocios;
using Model.Datos;
using excel = OfficeOpenXml;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AntCore.Controllers.CargaCalificaciones
{
    public class CargaCalificacionesController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        SiniestroNegocio objSiniestrosNeg;

        List<SelectListItem> listaCodificaciones = new List<SelectListItem>();
        List<SelectListItem> listaCodificacionesSin = new List<SelectListItem>();
        public CargaCalificacionesController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
            objSiniestrosNeg = new SiniestroNegocio();
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.ListaCodificaciones = listaCodificaciones;
            ViewBag.listaCargaCalificacionesPorFecha = objSiniestrosNeg.ListaverificarCalificacionesPorFecha("", "");
            return View();
           // ViewBag.listaCargaCalificacionesPorFecha = objSiniestrosNeg.ListaverificarCalificacionesPorFecha("", "");
        }
        public IActionResult Vista()
        {
            ViewBag.listaCargaCalificacionesPorFechaVista = objSiniestrosNeg.ListaverificarCalificacionesPorRangoFecha("", "",0);
            ViewBag.listaProvincias = objSiniestrosNeg.listaProvinciasEditVista();
            return View();
        }
        public JsonResult ProcesarVista(string fecinical, string fecFin, int codprov)
        {
            string mensajeError = "";
            string mensajeOk = "";
            var jsonResult = objSiniestrosNeg.ListaverificarCalificacionesPorRangoFecha(fecinical, fecFin, codprov);
           
            return Json(jsonResult);
        }

        public async Task<ActionResult> Validar(ICollection<IFormFile> file,string feccal,string reemplazar)
        {
            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "uploadsCal");
            string mensajeError = "", mensajeOk="";
            if (reemplazar == null || reemplazar == "")
                reemplazar = "NO";
            int count = 0;
            int codprov = 0;
            string anio = "", mes = "";
            var _fecha = feccal.Split('-');
            anio = _fecha[0].ToString();
            mes = _fecha[1].ToString();
            if (feccal == null || feccal == "")
            {
                mensajeError = "Ingrese la fecha";
            }
            else if (file.Count == 0)
            {
                mensajeError = "Seleccione un archvio";

            }
            else if (objSiniestrosNeg.ListaverificarCalificacionesPorFecha(anio, mes).Count() > 0 && reemplazar == "NO")
            {
                mensajeError = "Para la fecha seleccionada ya existen calificaciones cargadas, si desea reemplazar favor habilitar la opción Reemplazar calificaciones.";
            }
            else
            {
                try
                {
                    List<Modelo.Entity.Calificaciones> listaCal = new List<Modelo.Entity.Calificaciones>();
                    foreach (var f in file)
                    {
                        if (f.Length > 0)
                        {

                            var fileStream = new FileStream(Path.Combine(uploads, f.FileName), FileMode.Create);
                            await f.CopyToAsync(fileStream);
                            fileStream.Dispose();

                            //string fileName = $@"/{f.FileName}";//esta line para linux
                            string fileName = f.FileName;// ;//esta line para win
                          //  fileName = fileName.Replace(".xlsx","_" + DateTime.Now.ToString("yyyy-mm-dd")+".xlsx");
                            string fileContentType = f.ContentType;
                            byte[] fileBytes = new byte[f.Length];
                            //string sWebRootFolder = _hostingEnvironment.WebRootPath + "\\uploadsCal";  //esta line para win
                            
                            string sWebRootFolder = _hostingEnvironment.WebRootPath + "/uploadsCal/";  //esta line para linux
                            FileInfo files = new FileInfo(Path.Combine(sWebRootFolder, fileName));
                            using (var package = new ExcelPackage(files))
                            {
                                var currentSheet = package.Workbook.Worksheets;
                                var workSheet = currentSheet.First();
                                var noOfCol = workSheet.Dimension.End.Column;
                                var noOfRow = workSheet.Dimension.End.Row;
                                string hoja1 = workSheet.Name;
                               
                                for (int rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                                {
                                    Calificaciones obj = new Calificaciones();
                                    Model.Datos.CargaDropDownList objs = new Model.Datos.CargaDropDownList();
                                    obj.feccal = feccal.ToString();
                                    obj.nombreProvincia = workSheet.Cells[rowIterator, 1].Value.ToString();
                                    obj.cumcal = workSheet.Cells[rowIterator, 2].Value.ToString();
                                    obj.puncal = workSheet.Cells[rowIterator, 3].Value.ToString();
                                    obj.calcal = workSheet.Cells[rowIterator, 4].Value.ToString();
                                    obj.comcal = workSheet.Cells[rowIterator, 5].Value.ToString();
                                    obj.totcal = workSheet.Cells[rowIterator, 6].Value.ToString();
                                    listaCal.Add(obj);

                                    count++;

                                    string nombre_provincia = workSheet.Cells[rowIterator, 1].Value == null ? "" : workSheet.Cells[rowIterator, 1].Value.ToString();
                                    string valor_cumplimiento = workSheet.Cells[rowIterator, 2].Value == null ? "" : workSheet.Cells[rowIterator, 2].Value.ToString();
                                    string ValorPuntualidad = workSheet.Cells[rowIterator, 3].Value == null ? "" : workSheet.Cells[rowIterator, 3].Value.ToString();
                                    string ValorCalidad = workSheet.Cells[rowIterator, 4].Value == null ? "" : workSheet.Cells[rowIterator, 4].Value.ToString();
                                    string ValorCompromiso = workSheet.Cells[rowIterator, 5].Value == null ? "" : workSheet.Cells[rowIterator, 5].Value.ToString();
                                    string TotalCalificacion = workSheet.Cells[rowIterator, 5].Value == null ? "" : workSheet.Cells[rowIterator, 5].Value.ToString();
                                    int cont_prov = 0;

                                    if (nombre_provincia == "") { objs.codigo = count.ToString() + " - " + hoja1; objs.nombre = "El nombre de la provincia esta vacío" + " - " + " Celda {A -" + count + "} "; objs.codigo = count.ToString(); listaCodificaciones.Add(new SelectListItem() { Value = objs.codigo.ToString(), Text = objs.nombre.ToString() }); }
                                    if (nombre_provincia != "")
                                    {
                                        var provincias = objSiniestrosNeg.listaProvincias();
                                        foreach (var p in provincias)
                                        {
                                           
                                            if (p.nomprov == nombre_provincia)
                                            {
                                                cont_prov++;
                                                codprov = p.codprov;
                                            }
                                           

                                        }
                                        if (cont_prov == 0) { objs.codigo = count.ToString() + " - " + hoja1; objs.nombre = "El nombre de la provincia es incorrecto, favor revisar que no tenga tildes" + " - " + " Celda {A -" + count + "} "; objs.codigo = count.ToString(); listaCodificaciones.Add(new SelectListItem() { Value = objs.codigo.ToString(), Text = objs.nombre.ToString() }); }
                                    }
                                    try
                                    {
                                        decimal _valor_cumplimiento = Convert.ToDecimal(valor_cumplimiento);
                                    }
                                    catch (Exception ex)
                                    {
                                        objs.codigo = count.ToString() + " - " + hoja1; objs.nombre = "El valor de cumplimiento tiene un formato incorrecto, el valor debe ser un decimal con el separdor de decimales (.) ejemplo 0.30" + " - " + " Celda {B -" + count + "} "; listaCodificaciones.Add(new SelectListItem() { Value = objs.codigo.ToString(), Text = objs.nombre.ToString() });
                                    }
                                    try
                                    {
                                        decimal _ValorPuntualidad = Convert.ToDecimal(ValorPuntualidad);
                                    }
                                    catch (Exception ex)
                                    {

AntCore/src/AntCore/Views/CargaCalificaciones/Index.cshtml
  
@model Modelo.Entity.Calificaciones

<br />
<br />
<br />
<a class="btn btn-link active"  asp-action="Vista" asp-controller="CargaCalificaciones" id="btnVerVistaCal"> Vista Calificaciones</a>
<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>  Carga Calificaciones...</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @*// <form asp-action="Validar" class="form-control-static">*@

                    @using (Html.BeginForm("DownloadFormatoCargaCalificaciones", "CargaCalificaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <p class="fa fa-download"> </p> <input type="submit" value="Formato Carga Calificaciones" name="formatoCargaCalificaciones" class="btn btn-link btn-xs" />
                    }
                    @using (Html.BeginForm("Validar", "CargaCalificaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="form-group">
                            <div class="col-xs-12 col-sm-4 col-md-3 col-lg-5">
                            </div>
                            <label>  </label>  <img src="~/images/excel.jpg" height="50" /> EXCEL
                        </div>
                        <div class="form-group">
                            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-2">
                                <label>
                                    Fecha *
                                   
                                </label>
                              
                            </div>
                            
                                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                                    
                                    @Html.TextBoxFor(a => Model.feccal, null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top" })
                                </div>
                                <div class="col-xs-1 col-sm-4">
                                 
                                    @Html.CheckBox("ch_reemplazar")Reemplazar calificaciones
                                        
                                        @Html.TextBox("reemplazar", null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top", style="display:none" })
                                   
                                </div>
                                     
                               
                            
                        </div>
                        <div class="form-group">
                            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-4">
                               
                              
                            </div>
                        </div>
                       <br />
                    <br />
                    <br />
                            <div class="form-group">
                                <br />
                                <img src="~/images/carpeta.jpg" height="40" /> <label>Seleccionar archivo...</label>
                                <input type="file" name="file" id="file" />
                            </div>
                         
                            <div class="form-group" id="divBtnCargar">
                                <input id="btnCargar" type="submit" value="Cargar archivo" class="btn btn-primary btn-lg btn-block" />

                            </div>
                            <div class="progress" style="display:none">
                                <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar"
                                     aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                                    Cargado 100%...
                                </div>
                            </div>
                            @if (@ViewBag.mensajeValidacion != "")
                            {

                                <div class="form-group">
                                    <div ID="panelMensajeCal" Class="active smaller">
                                        <div id="divMensajeCal" class="alert alert-block alert-success fade in smaller">
                                            <strong><label ID="mensajeStrongLabelCal"> </label></strong>
                                            <label ID="mensajeLabelCal">@ViewBag.mensajeValidacion</label>
                                        </div>
                                    </div>

                                </div>
                            }
                        @if (@ViewBag.mensajeError != "")
                        {

                            <div class="form-group">
                                <div ID="panelMensajeCalE" Class="active smaller">
                                    <div id="divMensajeCalE" class="alert alert-block alert-danger fade in smaller">
                                        <strong><label ID="mensajeStrongLabelCalE"> </label></strong>
                                        <label ID="mensajeLabelCalE">@ViewBag.mensajeError</label>
                                    </div>
                                </div>

                            </div>
                        }

                    }
                   

                </div>
            </div>
            <div class="col-lg-5">
                <div class="row" id="divCalificaciones">

                    <table class="table small" id="dt_codificaciones">
                        <thead>

                            <tr class="bg-primary">

                                <th>#Registro</th>
                                <th>Descripcion</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var objSin in ViewBag.ListaCodificaciones)
                            {
                                <tr>
                                    <td>Fila- @objSin.Value</td>
                                    <td>@objSin.Text</td>
                                </tr>
                            }
                        </tbody>



                    </table>
                </div>
            </div>
       
        </div>
    </div>
    <div class="content-border">
        <div class="form-group">
            <div class="panel-body">
                <div class="row">
                    <div class="class="col-xs-3 col-sm-3 col-md-3 col-lg-10">
                        <div class="col-lg-10">
                            <div class="row" id="divCalificaciones">

                                <table class="table small" id="dt_calificaciones">
                                    <thead>

                                        <tr class="bg-primary">

                                            <th>Fecha</th>
                                            <th>Provincia</th>
                                            <th>V. Cumplimiento</th>
                                            <th>V. Puntualidad</th>
                                            <th>V. Calidad</th>
                                            <th>V. Compromiso</th>
                                            <th>T. Calificacion</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var objSin in ViewBag.listaCargaCalificacionesPorFecha)
                                        {
                                            <tr>

                                                <td>@objSin.feccal</td>


                                                <td>@objSin.nombreProvincia</td>
                                                <td>@objSin.cumcal</td>
                                                <td>@objSin.puncal</td>
                                                <td>@objSin.calcal</td>
                                                <td>@objSin.comcal</td>

                                                <td>@objSin.totcal</td>


                                            </tr>
                                        }
                                    </tbody>



                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 


    <div class="panel-footer">
        ........
    </div>
</div>

<!-- /.col-lg-4 -->

AntCore/src/AntCore/Views/CargaCalificaciones/Vista.cshtml
@model Modelo.Entity.Calificaciones

<br />
<br />
<a class="btn btn-link active" asp-action="Index" asp-controller="CargaCalificaciones" id="btnVerCal"> Carga Calificaciones</a>
<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>  Vista Calificaciones...</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                        @if (@ViewBag.mensajeError != "")
                        {

                            <div class="form-group">
                                <div ID="panelMensajeCalE" style="display:none" Class="active smaller">
                                    <div id="divMensajeCalE" class="alert alert-block alert-danger fade in smaller">
                                        <strong><label ID="mensajeStrongLabelCalE"> </label></strong>
                                        <label ID="mensajeLabelCalE"></label>
                                    </div>
                                </div>

                            </div>
                        }
                                       
                   
                    
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-2">
                        Fecha inicio *
                        @Html.TextBoxFor(a => Model.fecinical, null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top" })
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-2">
                        Fecha Fin *
                        @Html.TextBoxFor(a => Model.fecFin, null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top" })
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        Provincia *
                        @* @Html.DropDownList("ddl_provincia", (List<SelectListItem>)ViewBag.ObtenerListaProvincias, new { @class = "form-control", @placeholder = "PROVINCIAS" })*@
                        @Html.DropDownListFor(m => Model.codprov, (List<SelectListItem>)ViewBag.listaProvincias, new { @class = "form-control", @placeholder = "PROVINCIAS" })
                    </div>

                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-2">
                        <br />
                        <div class="form-group" id="divProcesar">
                           
                            <input id="btnProcesar" type="submit" value="Procesar" class="btn btn-primary active" />
                            

                        </div>
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <br />
                        <div class="form-group" id="divDescargar">
                            @using (Html.BeginForm("DownloadCal", "CargaCalificaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <input type="submit" value="Descargar Excel" class="btn btn-success active" />
                                @Html.TextBox("tbFechaini", null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top", style = "display:none" })
                                @Html.TextBox("tbFechafin", null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top", style = "display:none" })
                                @Html.TextBox("tbcodprov", null, new { @class = "form-control", @placeholder = "aaa-mm-dd", @title = "Tooltip on top", style = "display:none" })
                            }
                           
                           

                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="col-lg-12">
                <div class="row" id="divCalificacionesVista">

                    <table class="table small" id="dt_calificacionesVista">
                        <thead>

                            <tr class="bg-primary">

                                <th>Fecha</th>
                                <th>Provincia</th>
                                <th>V. Cumplimiento</th>
                                <th>V. Puntualidad</th>
                                <th>V. Calidad</th>
                                <th>V. Compromiso</th>
                                <th>T. Calificacion</th>

                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var objSin in ViewBag.listaCargaCalificacionesPorFechaVista)
                            {
                                <tr>

                                    <td>@objSin.feccal</td>


                                    <td>@objSin.nombreProvincia</td>
                                    <td>@objSin.cumcal</td>
                                    <td>@objSin.puncal</td>
                                    <td>@objSin.calcal</td>
                                    <td>@objSin.comcal</td>

                                    <td>@objSin.totcal</td>


                                </tr>
                            }*@
                        </tbody>



                    </table>
                </div>

            </div>
        </div>
    </div>
    <div class="content-border">
        <div class="form-group">
            <div class="panel-body">
                <div class="row">
                    <div class="class=" col-xs-3 col-sm-3 col-md-3 col-lg-6"">

                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="panel-footer">
        ........
    </div>
</div>